
/* IMPORTANT INSTRUCTIONS FOR LEARNERS
1) DO NOT CHANGE THE ORDER OF COLUMNS.
2) YOUR QUERY SHOULD DISPLAY COLUMNS IN THE SAME ORDER AS MENTIONED IN ALL QUESTIONS.
3) YOU CAN FIND THE ORDER OF COLUMNS IN QUESTION TEMPLATE SECTION OF EACH QUESTION.
4) USE ALIASING AS MENTIONED IN QUESTION TEMPLATE FOR ALL COLUMNS
5) DO NOT CHANGE COLUMN NAMES*/
                   
-- Question 1 (Marks: 3)
-- Objective: Determine, for flights that actually departed later than scheduled, what the departure delay is (in minutes).
-- Calculate the Delay in Departures for Delayed Flights
-- Question Template: Display following columns flight_id, flight_no, departure_delay_minutes

-- Write your SQL solution here

# NOTE: I APOLOGISE THAT I DIDNOT SAW THIS SHEET UNTIL TODAY DURING SUBMISSION HENCE I HAVE PREPARED ALL THE ANSWERS BASED ON PDF QUESTIONNARIES AND NOT BASED ON THE GUIDED STATEMENTS THAT WAS PROVIDED IN THIS SHEET. 
# NOTE: I DIDNOT GOT TIME TO CHECK THE TABLE FORMAT AS PER MY LAST UPDATED SQL SCRIPTS. I COULD REPREPARE IF I CAN GET SOME MORE TIME PERIOD.
use airlines_data;
select * from aircrafts;
select * from airports;
select * from boarding_passes;
select * from bookings;
select * from flights;
select * from seats;
select * from ticket_flights;
select * from tickets;


# ANS 1
select flight_id,flight_no, timestampdiff(minute,scheduled_departure,actual_departure) as departure_delay_minutes from flights where actual_departure is not null group by flight_id  order by departure_delay_minutes desc;

# ANS 2 VARIANT : Avg Departure Delay for Total Flights
select avg(timestampdiff(minute,scheduled_departure,actual_departure)) as avg_departure_delay, count(flight_id) as total_flights from flights ;



-- Question 2 (Marks: 3)
-- Objective: Show how frequently each aircraft is used by counting the number of flights operated by each aircraft.
-- List Flights Grouped by Aircraft to See Usage Frequency
-- Question Template: Display following columns aircraft_code, total_flights, avg_flight_duration_minutes

-- Write your SQL solution here

select * from aircrafts;
select * from flights;

# ANS 
select flights.aircraft_code, count(flights.aircraft_code) as total_flights, avg(timestampdiff(minute,actual_departure,actual_arrival)) as avg_flight_duration_minutes from flights inner join aircrafts on flights.aircraft_code = aircrafts.aircraft_code group by aircrafts.aircraft_code;

-- Question 3 (Marks: 3)
-- Objective: Aggregate the total revenue generated by each flight by summing up the fare amounts from the ticket_flights table.
-- Calculate Total Revenue per Flight from the Ticket_Flights Table
-- Question Template: Display following columns flight_id, flight_no, total_revenue

-- Write your SQL solution here
select * from flights;
select * from ticket_flights;

 #ANS 
select ticket_flights.flight_id, flights.flight_no, sum(amount) as total_revenue from ticket_flights join flights on  flights.flight_id = ticket_flights.flight_id group by flights.flight_id order by total_revenue desc;

-- Question 4 (Marks: 3)
-- Objective: Examine boarding pass data to identify how passengers are being boarded by calculating the average boarding number per flight.
-- Analyze Boarding Numbers per Flight to Detect Patterns in Boarding Pass Allocation
-- Question Template: Display following columns flight_id, avg_boarding_no, total_boarding_passes

-- Write your SQL solution here

# ANS
  select flight_id,avg(boarding_no) as avg_boarding_no, count(boarding_no) as total_boarding_passes from boarding_passes group by flight_id order by total_boarding_passes desc;
  
  
-- Question 5 (Marks: 3)
-- Objective: Identify seat occupancy by comparing the number of boarding passes (occupied seats) to the total seats available on an aircraft.
-- Determine Occupancy per Aircraft
-- Question Template: Display following columns flight_id, flight_no, aircraft_code, total_seats, occupied_seats, occupancy_rate_percentage

-- Write your SQL solution here

 select * from aircrafts;
select * from airports;
select * from boarding_passes;
select * from bookings;
select * from flights;
select * from seats;
select * from ticket_flights;
select * from tickets;

 # ANS
 
 WITH total_seats AS (SELECT aircraft_code, COUNT(seat_no) AS total_seats FROM seats GROUP BY aircraft_code), occupied_seats AS (SELECT flight_id, COUNT(seat_no) AS occupied_seats FROM boarding_passes GROUP BY flight_id) SELECT f.flight_id, f.flight_no, f.aircraft_code,ts.total_seats, os.occupied_seats, ROUND((os.occupied_seats / ts.total_seats) * 100, 2) AS occupancy_rate_percentage FROM flights f JOIN total_seats ts ON f.aircraft_code = ts.aircraft_code LEFT JOIN occupied_seats os ON f.flight_id = os.flight_id ORDER BY f.flight_id;
 
 

-- Question 6 (Marks: 3)
-- Objective: Identify the three flights that generated the highest revenue based on ticket sales.
-- Top 3 Flights by Revenue
-- Question Template: Display following columns flight_id, flight_no, total_revenue

-- Write your SQL solution here

select * from flights;
select * from ticket_flights;
# ANS
# NOTE: flights 2354 > 26212 > 2364 in decreasing order of top revenue generation	
					
 select ticket_flights.flight_id, flights.flight_no, sum(amount) as total_revenue from ticket_flights join flights on flights.flight_id = ticket_flights.flight_id group by flight_id order by total_revenue desc;
 

-- Question 7 (Marks: 3)
-- Objective: Determine the average flight duration for each aircraft model, allowing you to see how flight performance might vary between different models.
-- Average Flight Duration by Aircraft Model
-- Question Template: Display following columns model, avg_duration_minutes

-- Write your SQL solution here
 
select * from aircrafts;
select * from flights;
 
 #ANS Also added additional information such as aircraft_code and total flights model-wise calculated for avg duration minutes
 
 select aircrafts.model, flights.aircraft_code, round(avg(timestampdiff(minute,actual_departure,actual_arrival)),0) as avg_duration_minutes,count(flight_id) as total_flights from flights join aircrafts on aircrafts.aircraft_code = flights.aircraft_code where actual_departure is not null group by aircraft_code order by avg_duration_minutes desc;
 

-- Question 8 (Marks: 3)
-- Objective: Count how many flights depart from each airport to assess airport activity levels.
-- Flight Count per Airport (Departure)
-- Question Template: Display following columns departure_airport, departure_flights

-- Write your SQL solution here

# ANS 1
select departure_airport, count(actual_departure) as departure_flights from flights where actual_departure is not null group by departure_airport order by departure_flights desc;

# ANS 2 ALSO ADDED AIRPORT NAME AND AIRPORT CITY IN ABOVE REPORT
select airports.airport_name,airports.city, departure_airport, count(actual_departure) as departured_flights from flights join airports on flights.departure_airport = airports.airport_code where actual_departure is not null group by departure_airport order by departured_flights desc;


-- Question 9 (Marks: 3)
-- Objective: Count how many flights depart from and arrive at each airport to assess airport activity levels.
-- Flight Count per Airport (Arrival)
-- Question Template: Display following columns arrival_airport, arrival_flights

-- Write your SQL solution here

# ANS 1
select arrival_airport, count(actual_arrival) as arrival_flights from flights join airports on flights.arrival_airport = airports.airport_code where actual_departure is not null group by arrival_airport order by arrival_flights desc;

# ANS 2 ALSO ADDED AIRPORT NAME AND AIRPORT CITY IN ABOVE REPORT

select airports.airport_name,airports.city, arrival_airport, count(actual_arrival) as arrival_flights from flights join airports on flights.arrival_airport = airports.airport_code where actual_departure is not null group by arrival_airport order by Total_arrived_flights desc;


-- Question 10 (Marks: 3)
-- Objective: Analyze trends in bookings over time by grouping bookings by date, counting total bookings, and summing up the revenue.
-- Daily Booking Trends
-- Question Template: Display following columns booking_date, total_bookings, total_revenue

-- Write your SQL solution here

# ANS
select cast(book_date as date) as booking_date, count(book_ref) as total_Bookings, sum(total_amount) as total_revenue from bookings group by cast(book_date as Date) order by cast(book_date as Date);


-- Question 11 (Marks: 3)
-- Objective: Identify the most common routes by counting the number of flights for each departure–arrival airport pair.
-- Frequent Routes Analysis
-- Question Template: Display following columns departure_airport, arrival_airports, flights_count

-- Write your SQL solution here

# ANS 1
select departure_airport,arrival_airport,count(flight_id) as flights_count from flights join airports on airports.airport_code = flights.departure_airport  group by departure_airport,arrival_airport order by flights_count;

# ANS 2 Departure_airport_name and Arrival Airport_name also added of airports here in report
select a1.airport_name  as Departure_airport_name, a2.airport_name as Arrival_airport_name, departure_airport,arrival_airport,count(flight_id) as Total_flights from flights join airports a1 on a1.airport_code = flights.departure_airport join airports a2 on a2.airport_code = flights.arrival_airport  group by departure_airport,arrival_airport order by total_flights;


-- Question 12 (Marks: 3)
-- Objective: Determine how many passengers boarded each flight by counting the boarding passes issued.
-- Passenger Boarding Summary per Flight
-- Question Template: Display following columns flight_id, passengers_boarded

-- Write your SQL solution here

select * from boarding_passes;

# ANS 
select flight_id, count(ticket_no) as passengers_boarded from boarding_passes group by flight_id order by passengers_boarded desc;


-- Question 13 (Marks: 3)
-- Objective: Assess the boarding process by calculating the average boarding order number for each flight, which may indicate the boarding strategy or sequence.
-- Average Boarding Number per Flight
-- Question Template: Display following columns flight_id, avg_boarding_no

-- Write your SQL solution here

# ANS 
with ticket_counts as (select flight_id, count(ticket_no) as boarding_no from boarding_passes  group by flight_id) select flight_id, boarding_no, avg(boarding_no) over() as average_boarding_no from ticket_counts;


-- Question 14 (Marks: 3)
-- Objective: Aggregate the total amount spent by each passenger across all their tickets by joining the tickets and ticket_flights tables.
-- Total Spend per Passenger
-- Question Template: Display following columns passenger_id, total_tickets, total_spent

-- Write your SQL solution here

select * from ticket_flights;
select * from tickets;

# ANS ORDER BY TOTAL SPENT DESC
select passenger_id, count(tickets.ticket_no) as total_tickets, sum(amount) as total_spent from tickets join ticket_flights on tickets.ticket_no = ticket_flights.ticket_no group by passenger_id order by sum(amount) desc;

# ANS ORDER BY TOTAL TICKETS DESC
select passenger_id, count(tickets.ticket_no) as total_tickets, sum(amount) as total_spent from tickets join ticket_flights on tickets.ticket_no = ticket_flights.ticket_no group by passenger_id order by total_tickets desc;
 

-- Question 15 (Marks: 3)
-- Objective: Analyze the distribution of ticket volume and revenue across different fare conditions.
-- Fare?Condition Distribution
-- Question Template: Display following columns fare_conditions, tickets_sold, total_revenue

-- Write your SQL solution here

# ANS
 select fare_conditions, count(ticket_no) as tickets_sold, sum(amount) as total_Revenue from ticket_flights group by fare_conditions order by sum(amount);
 

-- Question 16 (Marks: 3)
-- Objective: Aggregate total revenue generated by each departure?arrival airport route.
-- Revenue by Route
-- Question Template: Display following columns departure_airport, arrival_airport, total_route_revenue

-- Write your SQL solution here

select * from flights;
select * from ticket_flights;

# ANS 
select departure_airport,arrival_airport,sum(amount) as total_route_revenue from flights join ticket_flights on flights.flight_id = ticket_flights.flight_id group by flights.departure_airport,flights.arrival_airport order by total_route_revenue desc;




-- Question 17 (Marks: 2)
-- Objective: Identify the top 5 booking hours of the day by volume of bookings
-- Peak Booking Hours
-- Question Template: Display following columns booking_hour, bookings_count

-- Write your SQL solution here

select * from bookings;

# ANS Booking_count arranged in descending order

select hour(book_date) as Booking_hour, count(book_ref) as bookings_count from bookings group by hour(book_date) order by Bookings_count desc;



